POST http://localhost:4002/products
Content-Type: application/json

{
  "name": "suco",
  "price": 9
}

###
GET http://localhost:4002/products

###
GET http://localhost:4002/products/a698c17c-3200-471c-91ad-672dcb200029

###
PUT  http://localhost:4002/products/b7ad1e36-6116-4266-bea8-42aaf7743e06
Content-Type: application/json

{
  "name": "banana prata",
  "price": 3
}

###
DELETE http://localhost:4002/products/0a8512a5-90da-4661-b74a-a55ed5231db5